steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # WebGL 빌드 파일을 GCP 스토리지 버킷에 업로드
        gsutil rsync -r ./gzip_build gs://unity-webgl-builds-cloud-cloud-2024/webgl/

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # GCP VM에 파일 복사
        gcloud compute ssh ijkdijae1@unity-dev-instance --zone=asia-northeast3-a --command="mkdir -p /tmp/webgl/" --troubleshoot
        gcloud compute scp --recurse gs://unity-webgl-builds-cloud-cloud-2024/webgl/* ijkdijae1@unity-dev-instance:/tmp/webgl/ --zone=asia-northeast3-a
        gcloud compute ssh ijkdijae1@unity-dev-instance --zone=asia-northeast3-a --command="sudo mv /tmp/webgl/* /var/www/html/" --troubleshoot

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'ijkdijae1@unity-dev-instance'
      - '--zone=asia-northeast3-a'
      - '--command=sudo systemctl restart nginx'

timeout: "600s"
options:
  logging: CLOUD_LOGGING_ONLY
