steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 기존 WebGL 파일 삭제
        gsutil -m rm -r gs://unity-webgl-builds-cloud-cloud-2024/webgl/*

        # 새로운 WebGL 파일 업로드
        gsutil -m rsync -r ./gzip_build gs://unity-webgl-builds-cloud-cloud-2024/webgl/

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # GCP VM에서 GCS 버킷의 파일을 복사
        gcloud compute ssh ijkdijae1@unity-dev-instance --zone=asia-northeast3-a --command="
          sudo mkdir -p /tmp/webgl &&
          sudo gsutil -m rsync -r gs://unity-webgl-builds-cloud-cloud-2024/webgl/ /tmp/webgl &&
          sudo rm -rf /var/www/html/* &&
          sudo mv /tmp/webgl/* /var/www/html/ &&
          sudo chown -R www-data:www-data /var/www/html/ &&
          sudo chmod -R 755 /var/www/html/
        "

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'ijkdijae1@unity-dev-instance'
      - '--zone=asia-northeast3-a'
      - '--command=sudo systemctl restart nginx'

timeout: "600s"
options:
  logging: CLOUD_LOGGING_ONLY
