steps:
  # Unity WebGL 빌드 수행

      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/project'
      - 'unityci/editor:ubuntu-6000.0.28f1-webgl-3'
      - 'unity-editor'
      - '-batchmode'
      - '-nographics'
      - '-quit'
      - '-projectPath'
      - '/project'
      - '-executeMethod'
      - 'Builder.BuildWebGL'
      - '-logFile'
      - '/project/build.log'


  # 빌드 결과를 Cloud Storage에 업로드
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'builds/WebGL/*'
      - 'gs://unity-webgl-builds-${PROJECT_ID}/'

  # Cloud Run에 WebGL 결과 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'unity-webgl'
      - '--source'
      - './'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '3600s'

