steps:
    # Docker login using environment variables
    - name: 'gcr.io/cloud-builders/docker'
       entrypoint: 'bash'
       args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
       secretEnv: ['USERNAME', 'PASSWORD']
     - name: "gcr.io/cloud-builders/docker"
       entrypoint: 'bash'
       args: ['-c', 'docker run $$USERNAME/REPOSITORY:TAG']
       secretEnv: ['USERNAME']
 
      
  # Unity WebGL 빌드 수행

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'  # 먼저 이미지 풀하고
      - 'game-ci/unity3d:2022.3.16f1-webgl'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/project'
      - 'game-ci/unity3d:2022.3.16f1-webgl'
      - 'unity-editor'
      - '-batchmode'
      - '-nographics'
      - '-quit'
      - '-projectPath'
      - '/project'
      - '-executeMethod'
      - 'Builder.BuildWebGL'
      - '-logFile'
      - '/project/build.log'


  # 빌드 결과를 Cloud Storage에 업로드
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'builds/WebGL/*'
      - 'gs://unity-webgl-builds-${PROJECT_ID}/'

  # Cloud Run에 WebGL 결과 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'unity-webgl'
      - '--source'
      - './'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '3600s'
images: []

 availableSecrets:
   secretManager:
   - versionName: projects/cloud-2024-2024/secrets/docker-username/versions/1
     env: 'PASSWORD'
   - versionName: projects/cloud-2024-2024/secrets/docker-password/versions/1
     env: 'USERNAME'
